version: '3.8'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: notification_service_app:latest
    container_name: notification_service_app
    ports:
      - "3005:3005"
    env_file:
      - .env.docker
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3005/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
